name: Linux-Build

# Run this workflow every time a new commit pushed to your repository
on: 
  push:
    tags:
      - '*'

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  linux-build:
    # Name the Job
    name: Build the source for linux
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout repo content
        uses: actions/checkout@v2

      
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12'
          check-latest: true
      - name: Install dependencies
        run: npm install
      - name: Electron forge build
        run: npm run make


